adding volumes, off-nominal volumes, cleanup
JaqpottCTO/ASTM_UTMAPI pull request #19
Opened 2024-12-19 20:27 UTC by antonydevans

- In DSS spec: 
    - Add OffNominalVolumesExtent to OperationalExtents (OffNominalVolumesExtent doesn’t require resources)
    - Add list of resources to OperationalIntentReference
    - remove OperationalIntent, OperationalIntentDetails, Priority
- In OIM spec:
    - Add volumes and offnominalvolumes to OperationalInentDetails
    - Add priority to OperationalInentDetails

2025-01-07 21:27 UTC, clymera requested changes

2025-01-07 21:27 UTC, clymera commented on DSS/astm-uam-psu-dss-0.0.0.yaml
> +            $ref: '#/components/schemas/ResourceOccupation'
Are we trying to share the list of occupied resources and the time of crossing or time range of occupation here?  I don't think ResourceOccupation is the right schema for this - it is more about the OVNs of all the operations and was submitted with the volume which provided the duration of occupation.  If that was the intent, I think we have to use a different schema here.

2025-01-07 21:27 UTC, clymera commented on OIM/astm-uam-psu-oim-0.0.0.yaml
> +        volumes:
Do we need to share resource occupation details here?  If so, that info is not included in the Volume4D schema.

2025-01-13 19:43 UTC, antonydevans commented on DSS/astm-uam-psu-dss-0.0.0.yaml
> +            $ref: '#/components/schemas/ResourceOccupation'
Do you think we need everything in the ResourceExtent schema instead? Or just a subset of that (like ID and timing)?

2025-01-13 19:44 UTC, antonydevans commented on OIM/astm-uam-psu-oim-0.0.0.yaml
> +        volumes:
Good point. I can add resource_usage to the Volume4D schema as optional.

2025-02-05 20:22 UTC, chinseah1138 commented
I could not find $ref: '../DSS/astm-uam-psu-dss-0.0.0.yaml#/components/schemas/OperationalIntentDetails' for OperationalIntentForMonitoring schema in astm-uam-psu-dcb-0.0.0.yaml?

2025-02-05 22:30 UTC, antonydevans commented
Thanks @chinseah1138. You are correct - it was incorrectly pointing to the DSS spec. Should point to the OIM spec. I have updated it.

2025-02-07 00:48 UTC, chinseah1138 commented
I have a question about what 'capacity_type' = "INSTANTANEOUS" mean? In our https://github.com/nasa/uam-apis/blob/master/openapi/cis/cis_model.yml, we have FLOW_RATE_CONSTANT = Constant time rate of separation & FLOW_RATE_FIXED_BIN = Constraint values for number of operations within a fixed time bin with duration in seconds. 
- Fixed time bin should start at top-of-the-hour and evenly divide up an hour. For more details, see description for unit = seconds in ConstraintValue. We have been using FLOW_RATE_FIXED_BIN during UAM X4 simulation tests that some of you participated with NASA Ames.

2025-02-07 01:07 UTC, antonydevans commented
Thanks for the question @chinseah1138 . "INSTANTANEOUS" refers to a resource capacity that specifies the maximum number of operations that can be present in that resource at any given time. FLOW_RATE_FIXED_BIN would be the one used for X4 type capacity constraints. We should add a description (similar to what you have in the NASA spec).

2025-02-07 17:25 UTC, chinseah1138 commented
Looking at astm-uam-psu-ris-0.0.0.yaml, I have a question about 'status' in 'CurrentResourceStatus'. If 'status' = INACTIVE with a 'capacity_end_time' of 'active_capacity', does that mean after 'capacity_end_time', DCB will assume 'status' automatically reverts to ACTIVE?

2025-02-07 19:00 UTC, antonydevans commented
Great question @chinseah1138 . I would say no - only once status returns to ACTIVE would the capacities become relevant, whatever they are specified as. If the capacity_end_time has passed when the status returns to ACTIVE, then the resource capacity would be the default_capacity (unless another capacity was specified). But let's discuss at the next meeting.

2025-02-07 19:20 UTC, chuhan68 commented on CM/astm-uam-psu-cm-0.0.0.yaml
> +                $ref: '../OIM/astm-uam-psu-oim-0.0.0.yaml#/components/schemas/ErrorResponse'
I noticed that the OIM doesn't have an ErrorResponse schema, and it uses the one in DSS.

2025-02-07 20:13 UTC, antonydevans commented on CM/astm-uam-psu-cm-0.0.0.yaml
> +                $ref: '../OIM/astm-uam-psu-oim-0.0.0.yaml#/components/schemas/ErrorResponse'
Thanks for catching this @chuhan68 . I will correct this.

2025-02-08 00:22 UTC, chinseah1138 commented
> Great question @chinseah1138 . I would say no - only once status returns to ACTIVE would the capacities become relevant, whatever they are specified as. If the capacity_end_time has passed when the status returns to ACTIVE, then the resource capacity would be the default_capacity (unless another capacity was specified). But let's discuss at the next meeting.

Thanks for your quick response but I would like to discuss in our next meeting. When you say "default_capacity", are you talking about in 'default_capacity' in 'definition'?

2025-02-10 22:54 UTC, chuhan68 commented on DCB/astm-uam-psu-dcb-0.0.0.yaml
>    /dcb/v1/imbalance/intent:
I noticed that the response from this endpoint includes an array of TrajectoryPoint4D, which contains trajectory_property_array. However, since IntentTrajectoryPoint (from the request) doesn’t have this information, how does DCB obtain or derive it?

2025-02-10 23:34 UTC, chuhan68 commented on DCB/astm-uam-psu-dcb-0.0.0.yaml
> +      operationId: notifyResourceDetailsChanged
The operationId here is the same as the one in /dcb/v1/resource_details. Shouldn't operationId be unique across all operations in the API?

2025-02-10 23:52 UTC, chuhan68 commented on DCB/astm-uam-psu-dcb-0.0.0.yaml
> +              $ref: '../RIS/astm-uam-psu-ris-0.0.0.yaml#/components/schemas/PutResourceDetails'
I see that ResourceReference in DSS includes the ris_availability property, which uses the UssAvailabilityState schema. Based on the name, it seems to represent the availability of the Resource Information Service (RIS). 
However, I thought multiple RIS instances could run on a synchronized database, ensuring redundancy. Given that, how is ris_availability determined and utilized?

2025-02-11 21:40 UTC, chinseah1138 commented
I don't understand why in astm-uam-psu-ris-0.0.0.yaml, PUT /ris/v1/resource_details/{entityid}/capacities has possible error response code "412": description: The client attempted to transition the operational intent to Accepted or Activated while marked as Down in the DSS?

2025-02-11 22:30 UTC, chinseah1138 commented
I don't understand why in astm-uam-psu-ris-0.0.0.yaml, PUT /ris/v1/resource_details/{entityid}/capacities to "Submit a new or changed temporary resource capacity to a peer." has return ErrorReport for OK 201? "201":
          description: Future temporary capacities were successfully received.
          content:
            application/json:
              schema:
                $ref: '../DSS/astm-uam-psu-dss-0.0.0.yaml#/components/schemas/ErrorReport'

2025-02-12 18:33 UTC, chinseah1138 commented
I think in astm-uam-psu-oim-0.0.0.yaml there is an error with this $ref: '#../DCB/astm-uam-psu-dcb-0.0.0/components/schemas/ImbalanceResponse' for POST /oim/v1/imbalance

2025-02-12 22:12 UTC, antonydevans commented on DCB/astm-uam-psu-dcb-0.0.0.yaml
>      put:
A put is consistent with how a subscription is created in the DSS (there is a post there to query for subscriptions, which we could add). Let's discuss tomorrow.

2025-02-12 22:21 UTC, antonydevans commented on DCB/astm-uam-psu-dcb-0.0.0.yaml
>    /dcb/v1/imbalance/intent:
Good point, let’s discuss, but this seems to be an error. Not sure what the value is to defining IntentTrajectoryPoint differently to TrajectoryPoint4D.

2025-02-12 22:26 UTC, antonydevans commented on DCB/astm-uam-psu-dcb-0.0.0.yaml
> +      operationId: notifyResourceDetailsChanged
Agreed. Let's confirm with others. We may not need to specify this here (or in line 514).

2025-02-12 22:27 UTC, antonydevans commented on DCB/astm-uam-psu-dcb-0.0.0.yaml
> +              $ref: '../RIS/astm-uam-psu-ris-0.0.0.yaml#/components/schemas/PutResourceDetails'
This is a good topic for tomorrow. I was thinking an RIS would be more similar to a USS in that one RIS would serve a resource, but others may have different views.

2025-02-12 22:34 UTC, antonydevans commented
> I don't understand why in astm-uam-psu-ris-0.0.0.yaml, PUT /ris/v1/resource_details/{entityid}/capacities has possible error response code "412": description: The client attempted to transition the operational intent to Accepted or Activated while marked as Down in the DSS? What does operational intent state have to do with updating to RIS a resource future capacities?

Agree Chin. This is a mistake. The 413 description needs to be updated too.

2025-02-12 22:42 UTC, antonydevans commented
> I think in astm-uam-psu-oim-0.0.0.yaml there is an error with this $ref: '#../DCB/astm-uam-psu-dcb-0.0.0/components/schemas/ImbalanceResponse' for POST /oim/v1/imbalance

Correct - this is an error. Thanks for catching it.

2025-02-12 23:55 UTC, chinseah1138 commented
I think operational_intent_id in ContributingOperation schema defined in astm-uam-psu-dcb-0.0.0.yaml should be EntityID and not EntityOVN, no?

2025-02-13 17:51 UTC, chinseah1138 commented
I just pulled latest commit and I noticed in astm-uam-psu-ris-0.0.0.yaml there is a invalid reference $ref: '#/components/schemas/PutUssAvailabilityDetails', I think this schema is in astm-uam-psu-oim-0.0.0.yaml, correct?

2025-02-13 20:20 UTC, antonydevans commented on DCB/astm-uam-psu-dcb-0.0.0.yaml
> +      operationId: notifyResourceDetailsChanged
I changed them to be notifyResourceDetails for the POST and notifyResourceDetailsChanged for the PUT.

2025-02-13 20:27 UTC, antonydevans commented on DCB/astm-uam-psu-dcb-0.0.0.yaml
>    /dcb/v1/imbalance/intent:
This endpoint is used by the OIM to send the DCB the desired trajectory. The OIM would likely not know what the resources are at this time, so wouldn't be able to include resource entry and exit points. But the DCB service will identify the resources and where the trajectory intersects it, so can add resource entry and exit points to the 4DT, which is what it returns. These points are the minimum needed to submit to the DSS.

2025-02-14 06:53 UTC, chuhan68 commented on DCB/astm-uam-psu-dcb-0.0.0.yaml
>    /dcb/v1/imbalance/intent:
I understand that the DCB is responsible for identifying any relevant resources along the trajectory provided in the request. However, I'm curious how the DCB derives and populates the trajectory properties in the TrajectoryPoint4D objects of the trajectory in the response, given that the request only includes IntentTrajectoryPoint objects (which do not have property arrays).

Also, does the DCB really need to return the entire trajectory in its response? In other words, are we expecting the DCB to modify (e.g., add or remove points) the original trajectory from the OIM?

2025-02-14 06:59 UTC, chuhan68 commented on DCB/astm-uam-psu-dcb-0.0.0.yaml
>      put:
Oh okay. I just wanted to confirm.

2025-02-14 07:12 UTC, chuhan68 commented on DCB/astm-uam-psu-dcb-0.0.0.yaml
> +              $ref: '../RIS/astm-uam-psu-ris-0.0.0.yaml#/components/schemas/PutResourceDetails'
Thanks for clarifying. I see the logic, and as long as we're not restricting an RIS to only one resource, I have no concern.

2025-02-14 19:15 UTC, clymera approved these changes

2025-02-17 16:20 UTC, merged